[package]
name = "crunchy-vdf"
version = "0.1.0"
authors = ["Magnus Larsen <golgothasTerror101@gmail.com>"]
edition = "2018"

[dependencies]
jemallocator = "0.3.2"
pest = "2.1.3"
pest_derive = "2.1.0"
